project:
  type: book
  output-dir: docs

book:
  title: "EL-2007 Sinyal dan Sistem"
  author: "Armein Z R Langi"
  date: "9/3/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - kuliah/materi_1.qmd
    - kuliah/materi_2.qmd
    - kuliah/materi_3.qmd
    - kuliah/materi_4.qmd
    - kuliah/materi_5.qmd
    - kuliah/materi_6.qmd
    - kuliah/materi_7.qmd
    - ujian/uts.qmd
    - kuliah/materi_8.qmd
    - kuliah/materi_9.qmd
    - kuliah/materi_10.qmd
    - kuliah/materi_11.qmd
    - ujian/uas.qmd   
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



